### ISSUE TITLE
Problem with running the project

### ISSUE THREAD

**Issue by LukaszGrela** [pixijs/pixi-examples-v2#1]
I've cloned the project and tried to run the commands
`npm run start` and `npm run jspm-start` but both end up with following error

```
http-server@0.9.0 C:\Users\[user]\AppData\Roaming\npm\node_modules\http-server
├── opener@1.4.1
├── corser@2.0.0
├── colors@1.0.3
├── http-proxy@1.14.0 (eventemitter3@1.2.0, requires-port@1.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── union@0.4.4 (qs@2.3.3)
├── ecstatic@1.4.1 (url-join@1.1.0, mime@1.3.4, minimist@1.2.0, he@0.5.0)
└── portfinder@0.4.0 (async@0.9.0, mkdirp@0.5.1)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "jspm-start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! pixi-examples-v2@1.0.0 postjspm-start: `npm install -g http-server && http-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixi-examples-v2@1.0.0 postjspm-start script 'npm install -g http-server && http-server'.
npm ERR! This is most likely a problem with the pixi-examples-v2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install -g http-server && http-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls pixi-examples-v2
npm ERR! There is likely additional logging output above.
```

**Comment by ivanpopelyshev** [comment]
something is running on port 8080 on your comp. May be its skype.

**Comment by LukaszGrela** [comment]
I'll check, more likely mongoose local server, thank you.

**Comment by ivanpopelyshev** [comment]
http-server -c-1 -p8081 will solve that :) Use the other port!

**Comment by GoodBoyDigital** [comment]
sounds fixed!
